version: "3.9"

services:
  app:
    container_name: ticket-booking
    build: .
    ports:
      - "26367:26367"
    env_file:
      - .env
    volumes:
      - .:/src/app
    networks:
      - app-network
    command: air -c .air.toml
    restart: always

networks:
  app-network:
